input_data_path: "data/heart_cleveland_upload.csv"
output_model_path: "models/model.pkl"
output_encoder_path: "models/encoder.pkl"
metric_path: "models/metrics.json"
splitting_params:
  val_size: 0.2
  random_state: 42
train_params:
  model_type: "RandomForestClassifier"
  n_estimators: 100
  random_state: 42
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  features_to_drop: []
  target_col: "condition"