apiVersion: v1
kind: Pod
metadata:
  name: online-inference-pod-probes
spec:
  containers:
  - name: online-inference-probes
    image: yessen3103/online_inference:v2
    ports:
    - containerPort: 80
    readinessProbe:
      initialDelaySeconds: 40
      periodSeconds: 20
      timeoutSeconds: 60
      httpGet:
        scheme: HTTP
        path: /health
        port: 80
    livenessProbe:
      httpGet:
        scheme: HTTP
        path: /health
        port: 80
      initialDelaySeconds: 50
      periodSeconds: 10